### ISSUE TITLE
Merge review checklist

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#99]
The purpose of this issue is to gather checks/tasks that should be done for every merge to the main branch. It can be closed when all of the tasks are either automated via github's actions or hooks or whatever they are, or have been documented in the code standards (see #69) or other appropriate place in the project's documentation in its repository. The next comment will be a starting list of tasks.

**Comment by gwhitney** [comment]
1) `npm run test:vue` and make sure everything passes.
2) `npm run lint` (waiting on #100, right now the repository abysmally fails. I do not think we need to separately run `npm run format-check` because I think that if `npm run lint` succeeds, it's guaranteed that `format-check` will not recommend any changes. @liam-mulhall does that seem right, or do you think the `format-check` needs to be added as a separate step?
3) Read over code changes, verifying that new code appears to be up to our coding guidelines, especially on points that cannot be automatically checked by tools. Also check that the code is readable/understandable, commented where need be, and seems sensible for the purpose at hand.
4) Run the code locally and perform whatever actual checks of its behavior will put the new feature, and the system as a whole, "through its paces."

Additional items that should always be checked before merging a pull request are welcome. Please post them here.

**Comment by gwhitney** [comment]
5. Make sure any changes that need to be are properly commented/documented as appropriate. This will become easier once we've resolved #71, but it's important even in the meantime.

**Comment by liam-mulhall** [comment]
Make sure `npm run build` succeeds.

**Comment by liam-mulhall** [comment]
Some of the items in @gwhitney's list will change if https://github.com/numberscope/frontscope/pull/123 is merged.

**Comment by gwhitney** [comment]
Agreed; a new list should be drafted post-Vue3.

**Comment by liam-mulhall** [comment]
I think we can update this list for frontscope now. Feel free to edit this draft:

- [ ] Write or supplement test(s) for the file(s) you touch in your PR.
- [ ] Make sure your PR is passing lint by running `npm run lint:check`.
- [ ] Make sure your PR is type correct by running `npm run typecheck`.
- [ ] Make sure your PR passes all tests. (Right now, just by running `npm run test:unit`.)
- [ ] <Insert documentation instructions here.>

Check the browser console (right click on your browser window > Inspect > Click the console tab) and make sure there aren't any:
- [ ] logs
- [ ] warnings
- [ ] errors

**Comment by gwhitney** [comment]
The excellent first draft seemed to me to be a combination of two checklists, one for the PR _submitter_ and one for the PR reviewer, so I took the liberty of separating the two, and there were enough individual edits that I just re-posted the checklists here:

The PR submitter should:

- [ ] Write or supplement test(s) for the file(s) you touch in your PR.
- [ ] (Insert documentation instructions here.)
- [ ] Make sure Numberscope runs properly, including former supposedly unmodified behaviors and newly implemented ones. In particular, run it via 'npm run dev' and with the browser console open and make sure there are no log messages from Numberscope code, warnings, or errors.

[As far as I can see, the other checks are implemented in the pre-commit hooks.]

The PR reviewer should make sure that:

- [ ] All new or changed features are appropriately documented.
- [ ] Tests are appropriately modified for all new or changed features.
- [ ] The PR is passing lint by running `npm run lint`. There should be no changed files and no warnings/errors.
- [ ] The PR builds by running `npm run build`. (This also checks type correctness.) There should be no errors, and for now the only allowed warning is the one about some assets being too big.
- [ ] The PR passes all tests. (Right now, just by running `npm run test:unit`.)
- [ ] Numberscope runs properly -- basically the same check as on the submitter list, but be sure to exercise as many randomly selected behaviors as you have time for, definitely including but not limited to the ones nominally affected by the PR.

Thoughts?
